{
 "title": "Python exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Website is accessible",
   "type": "gauge",
   "description": "1 = True\n0 = False",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Response time rate (1m)",
   "type": "timeseries",
   "description": "Rate of response time in a 1m window",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(request_processing_seconds_sum[1m]) / irate(request_processing_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Average response time (s)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(request_processing_seconds_sum / request_processing_seconds_count)"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_processing_seconds_count"
    }
   ]
  }
 ]
}